languge: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t tommyhung73/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tommyhung73/docker-react npm run test -- -- coverage
